src/posts/forms.py
# posts/forms.py
# file creates all the input form for making a post 
#


from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired



Game_Choices = [('al', 'Apex Legends'),('arma', 'Arma 3'),('bb', 'Baseball'),('bball', 'Basketball'),('bil', 'Billiards'),('bg', 'Board Games'),('cod', 'Call of Duty'),('csgo', 'Counter-Strike: Global Offensive'),('dayz', 'DayZ'),('dd', 'Dungeons & Dragons'),('db', 'Dodgeball'),('ft', 'Fortnite'),('fb', 'Football'),('gmod', 'Garry\'s Mod'),('ha', 'Halo'),('hi', 'Hiking'),('kb', 'Kickball'),('lol', 'League of Legends'),('mg', 'Misc. Games'),('rust', 'Rust'),('sb', 'Smash Brothers'),('val', 'Valorant'),('vol', 'Volleyball'),('wow', 'World of Warcraft')] 

class PostForm(FlaskForm):
    game = SelectField('Game',[DataRequired()], choices=Game_Choices)
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class AddCommentForm(FlaskForm):
    body = StringField('Body', validators=[DataRequired()])
    submit = SubmitField('Post')

src/main/routes.py
# Main Routes.py
# File is responsible for handling the requests to the url and loading the correct page
#
#
#
#
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required
from src import db, bcrypt
from src.models import Post, User
from src.posts.forms import PostForm
from src.users.forms import LoginForm
from datetime import datetime
# querying
import sqlite3
from sqlite3 import Error



#Creating a blueprint instance
main = Blueprint('main', __name__)





@main.route('/', methods=["GET","POST"])
def landing_page():
    # the first page a user will see if they are not logged in already
    # The html will display a cover page for first time visitors with an option to sign in or register
    # Creates a login form in case user logs into page, or has links to register

    #If user is logged in -> redirect them to their content page
    if (current_user.is_authenticated):
        return redirect(url_for('main.home'))

    # User is not signed in -> login post logic
    form = LoginForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data): #if user exists and password is valid with database:
            #logs in user and gives remember option form
            login_user(user,remember=form.remember.data)
            next_page = request.args.get('next')#grabs page user was previously on
            return redirect(next_page) if next_page else redirect(url_for('main.home')) #returns user to original page if not put them to the home page
            
        else:#if login was not sucsessful: send flash message
            flash('Login unsucsessful. Check username and password', 'danger')
            return redirect("login.html", title='Login', form=form)


    return render_template('landing_page.html', form=form)
    
    






@main.route('/home')
@login_required
def home():
    # If user is not logged in, send them to the login page
    # else show the home content
    #

    if not (current_user.is_authenticated):
        return redirect(url_for('user.login'))

    page = request.args.get('page',1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)##posts per page:
    return render_template('home.html',posts=posts)


@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/contact_us')
def contact_us():
    return render_template('contact_us.html')

src/posts/routes.py
# posts Routes.py
# File is responsible for handling the requests to the url and loading the correct page
# Dealing with urls that have to do with creating/accessing posts
#




from flask import render_template, request, Blueprint, flash, redirect, url_for
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime
from src import db
from src.models import Post, Comment
from src.posts.forms import PostForm, Game_Choices #importing the post form and the available game choices
from src.posts.forms import AddCommentForm #importing the comment form 
# querying
import sqlite3
from sqlite3 import Error


#Creating a blueprint instance
posts = Blueprint('posts', __name__)



@posts.route("/post/new", methods=['GET','POST'])
@login_required #user must be loged in to post
def new_post():
    #Creating list of available games to make a post for:
    form = PostForm()
    


    if request.method == 'POST' and form.validate():
        # 
        # Retrieves the value for game selected creates a new post form
        # Add and commit new post form to database

        game = dict(form.game.choices).get(form.game.data)
        post = Post(title=form.title.data, content=form.content.data, author=current_user, game=game)
        #Commit the post to the post db
        db.session.add(post)
        db.session.commit()
        
        flash('Your post has been created', 'success')
        return redirect(url_for('main.home'))

    return render_template('create_post.html', title='New Post', form=form, legend="New Post", games=Game_Choices) #removed games=game_display



@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)



@posts.route("/post/<int:post_id>/comment", methods=["GET", "POST"])
@login_required
def comment_post(post_id):
    #post = Post.query.get_or_404(post_id)
    form = AddCommentForm()
    if form.validate_on_submit():
        #db.create_all()
        comment = Comment(body=form.body.data, article=post)
        db.session.add(comment)
        db.session.commit()
        flash("Your comment has been added to the post", "success")
        return redirect(url_for("post", post_id=post.id))
    return render_template('post.html', title="Comment", form=form)



@posts.route("/post/<int:post_id>/comment", methods=["GET", "POST"])
@login_required
def comment(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title="Comment", comment=comment)



# Route allows users to delete a post that they created
#
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required #need to be logged in to update a post
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
       abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required #need to be logged in to update a post
def delete_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if comment.author != current_user:
       abort(403)
    db.session.delete(comment)
    db.session.commit()
    flash('Your comment has been deleted!', 'success')
    return redirect(url_for('main.home'))
    

src/users/routes.py
#
#
#
#
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from src import db, bcrypt
from src.models import User, Post
from src.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from src.users.utils import save_picture

#creatiing blueprint instance:
users = Blueprint('users', __name__)



@users.route('/register', methods=['GET', 'POST'])
def register():
    #if user is authenticated bring them to sign in:
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    #else creating a registration form object to gather the 'User' model data:
    form = RegistrationForm()
    
    #Checking for user validation. validate_on_submit is a function from wtf_forms & flask
    if form.validate_on_submit():
        #first hash the users password using bcrypt module
        #then load the neccesary form entries into the db model for user
        #Use syntax: form.name.data to pull the var 'name's data
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        #Creating User db object
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw, zipcode=form.zipcode.data)

        #Adding & commiting new change(addition) to the database named 'db'
        db.session.add(user)
        db.session.commit()

        flash('Account has been created! Procede to log in', 'success')

    #If form validated and user made -> send to login. Else -> render register page again
        return redirect(url_for('users.login')) 
    return render_template('register.html', title='Register', form=form)



@users.route('/login',methods=['GET', 'POST'])
def login():
    #If current user is authenticated. route them to the home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    #Else: Create a login form to acquire login information

    #Creating login form
    form = LoginForm()

    #Checking if user validated and sent the form
    if form.validate_on_submit():

        #logging in a user with an email
        #1.) Query the User Table of the database. search by username. will check if the account has the same password
        #2.) decrypt the password

        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data): #if user exists and password is valid with database:
            #logs in user and gives remember option form
            login_user(user,remember=form.remember.data)
            next_page = request.args.get('next')#grabs page user was previously on
            return redirect(next_page) if next_page else redirect(url_for('main.home')) #returns user to original page if not put them to the home page
            
        else:#if login was not sucsessful: send flash message
            flash('Login unsucsessful. Check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)



@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))





#TODO: make posts query from newest to oldest instead of oldest to newest 
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    page = request.args.get('page',1, type=int)
    posts = Post.query.filter_by(user_id=current_user.id).paginate(page=page,per_page=5)##posts per page:
    form = UpdateAccountForm()
    if form.validate_on_submit():
        #<begin photo save logic>
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        #</end photo save logic>
        #updating db model from form elements
        current_user.username = form.username.data
        current_user.email = form.email.data #set new email
        current_user.bio = form.bio.data
        db.session.commit() #submitting changes to the data base
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account') )#redirect so another post isnt sent
    elif request.method =='GET':#populating user form 
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts)

    # page = request.args.get('page',1, type=int)
    # posts = Post.query.filter_by(user_id=current_user.id).paginate(page=page,per_page=5)##posts per page:
    # return render_template("account.html", posts=posts)






##user post page route
## This is where we can create a profile page
@users.route("/user/<string:username>")
def user_page(username):
    page = request.args.get('page',1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page,per_page=10)##posts per page:
    return render_template('user_page.html',posts=posts, user=user)

src/templates/account.html
{% extends "layout.html" %}
{% block content %}

<!-- FONT ICON SCRIPT -->
<script src='https://kit.fontawesome.com/a076d05399.js'></script>

<form method="POST" action="" enctype="multipart/form-data">
  {{ form.hidden_tag() }}
  <fieldset class="form-group">
      <legend class="border-bottom mb-4"><h3>Change Account Info</h3></legend>
      <div class="form-group" >
           <h4>{{ form.username.label(class="form-control-label") }}</h4>

          {% if form.username.errors %}
              {{ form.username(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                  {% for error in form.username.errors %}
                      <span>{{ error }}</span>
                  {% endfor %}
              </div>
          {% else %}
              {{ form.username(class="form-control form-control-lg") }}
          {% endif %}
      </div>
      <div class="form-group">
         <h4>{{ form.email.label(class="form-control-label") }}</h4>
          {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                      <span>{{ error }}</span>
                  {% endfor %}
              </div>
          {% else %}
              {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
      </div>

      <div class="form-group">
        <h4>{{ form.bio.label(class="form-control-label") }}</h4>
         {% if form.bio.errors %}
             {{ form.bio(class="form-control form-control-lg is-invalid") }}
             <div class="invalid-feedback">
                 {% for error in form.bio.errors %}
                     <span>{{ error }}</span>
                 {% endfor %}
             </div>
         {% else %}
             {{ form.bio(class="form-control form-control-lg") }}
         {% endif %}
     </div>

     


      <div class="form-group">
             <h4> {{ form.picture.label() }} </h4>
              {{ form.picture(class="form-control-file") }}
              {% if form.picture.errors %}
                  {% for error in form.picture.errors%}
                      <span class="text-danger">{{ error }}</span> </br>
                  {% endfor %}
              {% endif %}
      </div>
  </fieldset>
  <div class="form-group">
      {{ form.submit(class="btn btn-outline-info") }}
  </div>
</form>



<div class="profile content-section">
  <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">

  <div class="profile-details-block">

    <div class="profile-detail">
      <!--  Make conditional for first and last name so "NONE" is not displayed-->
      {% if current_user.firstname %}
        <h4> {{ current_user.firstname }} {{ current_user.last_name }}</h4>
      {% endif %}
    </div>

    <div class="profile-detail">
      <h6 class="username"> @{{ current_user.username }} </h6>
    </div>

    <div class="profile-detail">
      <h6 class="user-details">
        Zipcode: {{ current_user.zipcode }}
      </h6>
    </div>

    <!-- <div class="profile-detail">
      <h6 class="user-details">
        <i style='font-size:20px' class='far'>&#xf073;</i> Joined: #TODO: add new column in db
    </div> -->
    
    <div class="bio-block">
      {% if current_user.bio %}
        <p class="bio-text"> {{ current_user.bio }}</p>
      {% else %}
        <p class="bio-text">Currently no bio</p>
       {% endif %} 
    </div>

  </div>

  




{% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
              <div class="article-metadata">
                <h5 class="username" style="text-decoration: none; color: rgb(136,153,166);"> <a stlye="color:rgb(136,153,166);" href="{{url_for('users.user_page', username=post.author.username) }}">{{ post.author.username }}</a> </h5>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              </div>
              <h1> {{ post.game }}</h1>
              <h2><a class="article-title" href="{{url_for('posts.post', post_id=post.id )}}">{{ post.title }}</a></h2>
              <p class="article-content">{{ post.content }}</p>
            </div>

            {% if post.author == current_user %}
            <div>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
        {% endif %}
        </article>


        <!-- Delete Modal -->

        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModal"> Delete Post?</h5>
              </div>
              <div class="modal-body">
                <p class="delete-text" >This can't be undone and it will be removed from your profile and the timeline </p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
              </div>
            </div>
          </div>
        </div>




 {% endfor %}
<!-- SHOW POSTS BY USER -->


{% endblock %}

src/templates/create_post.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">


    <form method="POST" action=" {{ url_for('posts.new_post') }}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            

<!-- game select -->
            <div class="form-group" >
                {{ form.game.label(class="form-control-label") }}
 
                    {{ form.game }}
                 
                   
            </div>

<!-- title of post -->
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>

<!-- post content -->
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>



    <!-- submit -->
        </fieldset>
        <div class="form-group">
            <!-- <input type="submit"> -->
            {{ form.submit(class="btn btn-outline-info") }}
        </div> 
        <!-- <input type="submit"> -->
    </form>
</div>

{% endblock%}

src/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
              <div class="article-metadata">
                <h5 class="username" style="text-decoration: none; color: rgb(136,153,166);"> <a stlye="color:rgb(136,153,166);" href="{{url_for('users.user_page', username=post.author.username) }}">{{ post.author.username }}</a> </h5>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              </div>
              <h1> {{ post.game }}</h1>
              <h2><a class="article-title" href="{{url_for('posts.post', post_id=post.id )}}">{{ post.title }}</a></h2>
              <p class="article-content">{{ post.content }}</p>
            </div>

            {% if post.author == current_user %}
            <div>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
        {% endif %}
        </article>

        
        <!-- Delete Modal -->

        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModal"> Delete Post?</h5>
              </div>
              <div class="modal-body">
                <p class="delete-text" >This can't be undone and it will be removed from your profile and the timeline </p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
              </div>
            </div>
          </div>
        </div>







    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
      {% if posts.page==page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
        ...
      {% endif %}
    {% endfor %}


{%endblock%}

src/templates/layout.html
<!DOCTYPE html>


<!-- Start html code and page name -->
<html lang="en" dir="ltr">
  <head>
       <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">


    {% if title %}
        <title>Lets Play - {{ title }}</title>
    {% else %}
        <title>Lets Play</title>
    {% endif %}
  </head>
<!-- end html and page name -->





  <body>
    <!-- Entire site header -->
<header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">

            <!-- Left side nav shows app name -->
            <a class="nav-bar-title" href="{{ url_for('main.home')}}">Lets Play</a>
            <!-- dropdown nav bar if screen dimensions change -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>


              <!-- Top nav bar html -->
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}

                  <a class="nav-bar-item" href="{{ url_for('posts.new_post') }}">New Post </a>
                {% endif %}
            <!-- About us page -->      
             <div class="collapse navbar-collapse" id="navbarToggle"> 
                <a class="nav-bar-item" href="{{ url_for('main.about') }}">About</a>
                </div>
            <!-- About us page -->      
            <div class="collapse navbar-collapse" id="navbarToggle"> 
              <a class="nav-bar-item" href="{{ url_for('main.contact_us') }}">Contact</a>
              </div>

                <!--- add in a if user is authenticated for python browser programming-->
                </div>

                <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-bar-item" href="{{ url_for('users.logout') }}">Logout</a>
                <a class="nav-bar-item" href="{{ url_for('users.account') }}">Account</a>
                {% else %}
                    <a class="nav-bar-item" href="{{ url_for('users.login') }}">Login</a>
                    <a class="nav-bar-item" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
                </div>
            </div>
            </div>
        </nav>
        </header>

       
            <main role="main" class="container">
              <div class="row">
                  <div class="col-md-8">
                  {% with messages = get_flashed_messages(with_categories=true) %}
                      {% if messages %}
                          {% for catagory, message in messages %}
                          <div class="alert alert-{{ catagory }}">
                              {{ message }}
                          </div>
                          {% endfor %}
                      {% endif %}
                  {% endwith %}

                  {% block content %}{% endblock %}
                  </div> 
              </div> <!-- end content-->

              </main> <!-- end wrapper-->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
            <a class="mr-2" href="{{url_for('users.user_page', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
                <div>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
            </div>
            <h1 class='game-lable'> {{ post.game }} </h1>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>

    <!-- Comment Box -->

    <body>  
      <div class="info">
        <input id="example" type="text"
               name="Ntext" size="75">
        <input id="sent" type="submit"  
               value="Post"> 
    </div>
      <p id="para">      
      </p>
    </body>


    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="deleteModal"> Delete Post?</h5>
            </div>
            <div class="modal-body">
              <p class="delete-text" >This can't be undone and it will be removed from your profile and the timeline </p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <form action="{{url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                  <input class="btn btn-danger" type="submit" value="Delete">
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

src/templates/user_page.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{user.username }} ({{posts.total}})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="media-body">
              <div class="article-metadata">
                <a class="mr-2" href="{{url_for('users.user_page', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              </div>
              <h2><a class="article-title" href="{{url_for('posts.post', post_id=post.id )}}">{{ post.title }}</a></h2>
              <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
      {% if posts.page==page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('users.user_page',username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_page',username=user.username, page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
        ...
      {% endif %}
    {% endfor %}

{%endblock%}